apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.14.2
    app.quarkus.io/build-timestamp: 2024-11-02 - 07:56:12 +0000
  labels:
    app.kubernetes.io/name: config-operator
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: config-operator
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: config-operator
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.14.2
        app.quarkus.io/build-timestamp: 2024-11-02 - 07:56:12 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: config-operator
        app.kubernetes.io/version: 1.0-SNAPSHOT
      namespace: test
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: tarjei400/test:latest
          imagePullPolicy: Always

          name: config-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

