{{- $globalNamespace := .Release.Namespace }}
{{- $operatorName := include "external-config-operator.fullname" . }}
{{- $networkPolicyName := include "external-config-operator.networkPolicyName" . }}
{{- range $config := .Values.configurationStores }}
{{- $namespace := $config.namespace }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $networkPolicyName }}-{{ $config.name }}
  labels:
    app: {{ $operatorName }}-{{ $config.name }}-{{ $namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ $operatorName }}-{{ $config.name }}-{{ $namespace }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ $operatorName }}
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: {{ $operatorName }}
      ports:
        - port: {{ $config.containerPort }}
          protocol: TCP
---
{{- end }}